apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rotations
  name: rotations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rotations
  strategy: {}
  template:
    metadata:
      labels:
        app: rotations
    spec:
      containers:
      - image: rotations
        name: rotations
        command: 
        - /bin/sh
        - -c
        - 'uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080'
        env:
        - name: AWS_REGION
          value: us-west-2
        - name: QUEUES_TABLE_NAME
          value: karaoke-app-local-dev-queues
        - name: SINGERS_TABLE_NAME
          value: karaoke-app-local-dev-enqueued-singers
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rotations
  name: rotations
spec:
  ports:
  - name: 5003-8080
    nodePort: 32103
    port: 5003
    protocol: TCP
    targetPort: 8080
  selector:
    app: rotations
  type: NodePort

