version: "3.9"

services:
  job:
    build: ./src
    volumes:
      - ./src/:/usr/src/app/
    environment:
      - POSTGRES_HOSTNAME=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

volumes:
  postgres: