version: '3.8'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8083:8080
    environment:
      - QUEUES_TABLE_NAME=queues
      - ENQUEUED_SINGERS_TABLE_NAME=enqueued_singers
      - SONG_CHOICES_TABLE_NAME=song_choices