version: '3.8'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8082:8080
    environment:
      - DATABASE_URL=postgresql://singers_user:pa55w0RD@db/karaoke
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=singers_user
      - POSTGRES_PASSWORD=pa55w0RD
      - POSTGRES_DB=karaoke

volumes:
  postgres_data: