version: '3.9'

services:
  web:
    depends_on:
      - mongo
    build: ./src
    command: |
      uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8081:8080
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password1
    links:
      - mongo
  mongo:
    container_name: mongo 
    image: mongo:5.0.15-focal 
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password1

volumes:
  mongo_data: