name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test_and_deploy:
    name: "Test, Build & Push"
    runs-on: ubuntu-22.04
    permissions:
      id-token: write 
      contents: read 
    steps:
      - name: Checkout
        uses: actions/checkout@v3 
    
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::919980474747:role/github-actions
          aws-region: us-west-2 

      - name: Setup Python 3.10 
        id: python_setup 
        if: github.event_name == 'pull_request'
        uses: actions/setup-python@v4 
        with:
          python-version: '3.10.6'
          architecture: 'x64'

      - name: Install Python dependencies 
        id: python_dependencies
        working-directory: ./microservices/song_library/src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run unit tests
        id: unit_tests
        working-directory: ./microservices/song_library/src
        run: pytest 